config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get 'download_pdf', to: "search#download_pdf"
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  require 'media_wiki'
  require 'wikipedia'
  before_action :find_term

  def index
  end

  def download_pdf
  	pdf = WickedPdf.new.pdf_from_string(@page) 
     send_data(pdf, 
         :filename    => "#{@result.title}.pdf", 
         :disposition => 'attachment') 
 
    # pdf = render_to_string :pdf=>'search/download_pdf.pdf.erb',:margin => {:top=> 20,
    #                 :bottom => 10,
    #                 :left=> 10,
    #                 :right => 10},
    #                 :orientation => 'Landscape',
    #                 :page_size=>'A4',
    #                 :type=>"application/pdf",
    #                 filename: "search/download_pdf.pdf.erb"
    # send_file pdf

  end

  private

  def find_term
  	@result = Wikipedia.find( params[:term])
  	@page = Wikitext::Parser.new.parse(@result.content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikipediaDownloadSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/download_pdf.pdf.erb
  	<div id="content_class">
		<%=h @page.html_safe %>
  	</div>

app/views/search/index.html.erb
<div class="card text-center">
  <div class="card-header">
  	<h3> Results </h3>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="card border-0">
      <div class="card-body">
        <p class="card-text mt-2"><u><%= link_to "#{@result.title}", @result.fullurl, class: "card-link float-right", target: "_blank"%></u></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card border-0">
      <div class="card-body">
        <p class="card-text"><%= link_to "Download as PDF", download_pdf_path(term: @result.title), class: "btn btn-primary card-link"%></p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
   <div class="row justify-content-center search-section">
                        <div class="col-12 col-md-10 col-lg-8">
                           <h3 class="text-center">Wikipedia Content Search</h5><br />
                            <%= form_tag(search_path, method: 'get',class: "card card-sm search-form") do %>
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>
                                    <!--end of col-->
                                    <div class="col">
                                       <%= text_field_tag :term, "", class: "form-control form-control-lg form-control-borderless search-input", placeholder: "Search topics or keywords" %>
                                    </div>
                                    <!--end of col-->
                                    <div class="col-auto">
                                      <%= submit_tag 'Search', class: "btn btn-lg btn-success search-button" %>
                                    </div>
                                    <!--end of col-->
                                </div>
                           <% end %>
                        </div>
                        <!--end of col-->
                    </div>
</div>